---
final_name: opentsdb-firehose-nozzle
blobstore:
  provider: s3
  options:
    bucket_name: opentsdb-blobstore
    host: s3.cn-north-1.amazonaws.com.cn
    endpoint: https://s3.cn-north-1.amazonaws.com.cn
