---
meta:
  <<: (( merge ))
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent 
    version: latest
  availability_zone: (( merge ))

jobs:
  - name: opentsdb-firehose-nozzle 
    instances: 2
    networks:
      - name: default
        static_ips: (( static_ips(0,1) ))

compilation:
  cloud_properties:
    instance_type: c3.large

resource_pools:
  - name: large 
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "c3.large" ))
      elbs: ~

networks: (( merge ))
